name: Deploy to GitHub Pages

# Run workflow on every push to the main branch.
on:
  push:
    branches: [ main ]

jobs:
  deploy-to-github-pages:
    # Use ubuntu-latest image to run steps on.
    runs-on: ubuntu-latest
    steps:
    # Use GitHub checkout action to checkout code from main branch.
    - uses: actions/checkout@v2

    # Setup .NET.
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.*

    # Publish Blazor project to the release folder.
    - name: Publish .NET Project
      run: dotnet publish TextManipulator.csproj -c Release -o release --nologo

    # Change the base-tag in index.html from '/' to 'TextManipulator' to match GitHub Pages repository subdirectory.
    - name: Change base-tag in index.html from / to TextManipulator
      run: sed -i 's/<base href="\/" \/>/<base href="\/TextManipulator\/" \/>/g' release/wwwroot/index.html

    # Copy index.html to 404.html to serve the same file when a file is not found.
    - name: copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html

    # Add .nojekyll file so GitHub pages doesn't treat this project as a Jekyll project. (Allow files and folders starting with an underscore)
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll

    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot
